### PR TITLE
 Upgrade Kafka Version from 1.0.0 to 1.1.1

### PR DESCRIPTION
**Pull request by Borjianamin98**
This change is [Reviewable](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8)

### CODE REVIEW

**Review by bozorgzadeh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @Borjianamin98 and @bozorgzadeh)

___
*[README.md, line 25 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvSHT96zXKrhsj80yw:-LuvSHT96zXKrhsj80yx:b-4l0t0f) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/README.md#L25)):*
> ```
>                 } catch (InterruptedException e) {
>                     return;  // We are interrupted as shut down process. So better to give it up.
>                 }
> ```

Remove it.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 285 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvWrgoC02kI_284N4E:-LuvWrgp9vAWRZ505l-U:b7k6xjs) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L285)):*
> ```
>             // Call poll will block until connected to kafka broker and get at least information.
>             // Using listTopics after poll because listTopics block until offset and metadata of each topic fetched or
>             // time out based on request timeout configuration (request.timeout.ms)
> ```
Remove it.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 298 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvVhbHASeO4fNOlWOe:-LuvVhbHASeO4fNOlWOf:b-8ncoi6) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L298)):*
> ```Java
>             executor.shutdown();
>         }
> ```

Check that the topic you want to read, is available from listTopics.
Unless you can throw AssertionError.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 442 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvcNKQ7SGL1Ou1wN15:-LuvcNKQ7SGL1Ou1wN16:bbkuh29) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L442)):*
> ```
> );
> ```
keepConnectionAlive();
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 445 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvchE26B-a459hMu8U:-LuvchE26B-a459hMu8V:b-lm52x8) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L445)):*
> ```
>             int lastPollTime = 0;
>             final double ratioOfKeepConnection = 0.5;
> ```
Remove it
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 446 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvdCwG9MPeS2Bco3qw:-LuvdCwG9MPeS2Bco3qx:by7xxd9) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L446)):*
> ```
>  0.5
> ```
0.7
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 449 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-Luvcj89EU24igbpIZDJ:-Luvcj89EU24igbpIZDK:b8evy9q) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L449)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                 if (lastPollTime >= (int) (ratioOfKeepConnection * maxPollIntervalMillis)) {
>                     keepConnectionAlive();
>                     lastPollTime = 0;
>                 }
> ```
</details>

Move it to keepConnectionAlive()
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 454 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvctGg86TbmvAiRjts:-LuvctGg86TbmvAiRjtt:b4i5flu) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L454)):*
> ```
> lastPollTime += 1;
> ```
keepConnectionAlive()
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 461 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvZW3z3drTtO2LR90T:-LuvZW3z3drTtO2LR90U:b-lw2fff) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L461)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>      * Consumer will not poll anything while retrying for adding polled record to queueRecords because queuedRecords is
>      * full. It may lead to timeout and consumer will be considered failed. We keep connection of kafka alive by
>      * calling poll periodically. Because poll() can return records, pause consumer before reading and resume it after.
>      */
> ```
</details>


Tries to keep the connection to Kafka alive by calling poll() but it first calls pause() to avoid receiving records on poll().
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 467 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-Luv_Zoi8oqdrQ5MVl1W:-Luv_Zoi8oqdrQ5MVl1X:bxef78w) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L467)):*
> ```
>         // Method poll of consumer called before call keepConnectionAlive method, so assignment of partitions
>         // happened for consumer. Create a copy of assigned partitions before pause and resume because rebalance during
>         // this process can cause problem. If rebalance happens, retry again.
> ```
Remove it.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 476 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvcxJx0glLGDu4A45a:-LuvcxJx0glLGDu4A45b:b-6enqjd) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L476)):*
> ```
> ;
> ```
set lastPoll before all call to poll() methods in this class.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 504 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvdP9pEAvx_N0LXETq:-LuvdP9pEAvx_N0LXETr:b-drw7x4) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L504)):*
> ```
> }
> ```
in method ack() remvoe while/sleep and InteruptedException from signature of the method. Just add the item to list.

**Review by Borjianamin98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @bozorgzadeh)

___
*[README.md, line 25 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvSHT96zXKrhsj80yw:-LuvkgoM8n1dRtwwyzPe:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/README.md#L25)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
>                 } catch (InterruptedException e) {
>                     return;  // We are interrupted as shut down process. So better to give it up.
>                 }
> ```

Remove it.
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 285 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvWrgoC02kI_284N4E:-LuvlGGg0ZVeVT7akgrY:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L285)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
>             // Call poll will block until connected to kafka broker and get at least information.
>             // Using listTopics after poll because listTopics block until offset and metadata of each topic fetched or
>             // time out based on request timeout configuration (request.timeout.ms)
> ```
Remove it.
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 298 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvVhbHASeO4fNOlWOe:-Luvms5u1K9KcCOzvUyG:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L298)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

Check that the topic you want to read, is available from listTopics.
Unless you can throw AssertionError.
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 442 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvcNKQ7SGL1Ou1wN15:-LuvqX081k5jQf2Qx92J:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L442)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
> );
> ```
keepConnectionAlive();
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 445 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvchE26B-a459hMu8U:-LuvqajB8QrXJmwFEy9r:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L445)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
>             int lastPollTime = 0;
>             final double ratioOfKeepConnection = 0.5;
> ```
Remove it
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 446 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvdCwG9MPeS2Bco3qw:-LuvqetJ7JlOBGZrtrlx:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L446)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
>  0.5
> ```
0.7
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 449 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-Luvcj89EU24igbpIZDJ:-Luvqn8x9s1lY5VUEiJG:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L449)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
>                 if (lastPollTime >= (int) (ratioOfKeepConnection * maxPollIntervalMillis)) {
>                     keepConnectionAlive();
>                     lastPollTime = 0;
>                 }
> ```
Move it to keepConnectionAlive()
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 454 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvctGg86TbmvAiRjts:-LuvqwO58QEIc9dWqlRy:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L454)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
> lastPollTime += 1;
> ```
keepConnectionAlive()
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 461 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvZW3z3drTtO2LR90T:-LuvrSwHDWm117tuUAsT:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L461)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
>      * Consumer will not poll anything while retrying for adding polled record to queueRecords because queuedRecords is
>      * full. It may lead to timeout and consumer will be considered failed. We keep connection of kafka alive by
>      * calling poll periodically. Because poll() can return records, pause consumer before reading and resume it after.
>      */
> ```

Tries to keep the connection to Kafka alive by calling poll() but it first calls pause() to avoid receiving records on poll().
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 467 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-Luv_Zoi8oqdrQ5MVl1W:-LuvrTJdBekR2o9trAGU:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L467)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
>         // Method poll of consumer called before call keepConnectionAlive method, so assignment of partitions
>         // happened for consumer. Create a copy of assigned partitions before pause and resume because rebalance during
>         // this process can cause problem. If rebalance happens, retry again.
> ```
Remove it.
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 476 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvcxJx0glLGDu4A45a:-LuvrVY815_WIuWMprzr:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L476)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
> ;
> ```
set lastPoll before all call to poll() methods in this class.
</blockquote></details>

Done.
___
*[src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java, line 504 at r1](https://reviewable.io/reviews/sahabpardaz/smart-commit-kafka-consumer/8#-LuvdP9pEAvx_N0LXETq:-Luvrih95bj8UO2EUn_0:b-896fix) ([raw file](https://github.com/sahabpardaz/smart-commit-kafka-consumer/blob/d887fd00f9f41e909fcc2627f1f7e6b3bd979cb3/src/main/java/ir/sahab/kafkaconsumer/SmartCommitKafkaConsumer.java#L504)):*
<details><summary><i>Previously, bozorgzadeh wrote…</i></summary><blockquote>

> ```
> }
> ```
in method ack() remvoe while/sleep and InteruptedException from signature of the method. Just add the item to list.
</blockquote></details>

Done.

**Comment by Borjianamin98** [comment]
> Revert it back
> Just one version.

Done

**Comment by Borjianamin98** [comment]
> 2.4

Done

**Comment by Borjianamin98** [comment]
> System.surrentTimeMillis()

Done

**Comment by Borjianamin98** [comment]
> System.currentTimeMillis()

Done

**Pull request merged**
